version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:30000/graphql
      - NEXTAUTH_URL=http://host.docker.internal:30000
    network_mode: host