export enum AuditCategoryType {
  CELLULE = "CELLULE",
  MOTEUR = "MOTEUR",
  AVIONIQUE = "AVIONIQUE",
  TRAIN_ATTERRISSAGE = "TRAIN_ATTERRISSAGE",
  SYSTEME_CARBURANT = "SYSTEME_CARBURANT",
  SYSTEME_ELECTRIQUE = "SYSTEME_ELECTRIQUE",
  DOCUMENTATION = "DOCUMENTATION",
  EQUIPEMENT_SECURITE = "EQUIPEMENT_SECURITE",
  AUTRE = "AUTRE",
}

export enum AuditFrequencyType {
  QUOTIDIEN = "QUOTIDIEN",
  HEBDOMADAIRE = "HEBDOMADAIRE",
  MENSUEL = "MENSUEL",
  TRIMESTRIEL = "TRIMESTRIEL",
  SEMESTRIEL = "SEMESTRIEL",
  ANNUEL = "ANNUEL",
  BIANNUEL = "BIANNUEL",
  HEURES_DE_VOL = "HEURES_DE_VOL",
  APRES_INCIDENT = "APRES_INCIDENT",
  AUTRE = "AUTRE",
}

export enum AuditResultType {
  CONFORME = "CONFORME",
  NON_CONFORME = "NON_CONFORME",
  CONFORME_AVEC_REMARQUES = "CONFORME_AVEC_REMARQUES",
  NON_APPLICABLE = "NON_APPLICABLE",
}

export enum CriticalityLevel {
  CRITIQUE = "CRITIQUE",
  MAJEUR = "MAJEUR",
  MINEUR = "MINEUR",
  INFO = "INFO",
}
